project_id = "ihmigjoaxuwiriiqkesk"

[functions.analyze-image]
verify_jwt = false

[functions.generate-perfect-day]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.generate-watch-notifications]
verify_jwt = false

[functions.explore-feed]
verify_jwt = false

[functions.contextual-recommendations]
verify_jwt = false

[functions.shared-availability]
verify_jwt = true

[functions.connect-media]
verify_jwt = true
