import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ArrowLeft, Globe } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";

const PrivacyPolicy = () => {
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();
  const language = i18n.language?.startsWith("es") ? "es" : "en";

  const toggleLanguage = () => {
    i18n.changeLanguage(language === "es" ? "en" : "es");
  };

  const spanishContent = {
    title: "POLÍTICA DE PRIVACIDAD",
    subtitle: "VYV (Visualize Your Vibe)",
    sections: [
      {
        heading: "1. Introducción",
        content: `Bienvenida a VYV ("nosotros", "nuestro/a"). En VYV te ayudamos a mejorar tu bienestar y productividad personal. Esta Política de Privacidad explica cómo recopilamos, usamos, compartimos y protegemos la información obtenida a través de la app, incluidas fotos, publicaciones y actividad social.
Al usar VYV, aceptas el tratamiento de datos conforme a esta política.

La aplicación está disponible en múltiples idiomas y puede ser utilizada en el idioma que el usuario prefiera. La interfaz, textos y mensajes se adaptarán automáticamente al idioma seleccionado, del mismo modo que lo hace Instagram.`
      },
      {
        heading: "2. Información que recopilamos",
        content: `• Datos proporcionados por ti (nombre, email, foto de perfil, publicaciones, imágenes, comentarios).

• Datos generados por tu uso de la app (horarios, hábitos, estadísticas, interacciones).

• Datos técnicos (IP, tipo de dispositivo, sistema operativo).

• Si decides vincular wearables o apps de salud, se podrán leer datos como pasos, horas de sueño o ritmo cardíaco.`
      },
      {
        heading: "3. Cómo usamos tu información",
        content: `• Para permitir la publicación y visualización de contenido.

• Personalizar tu experiencia y ofrecerte recomendaciones.

• Analizar el uso de la app y mejorarla.

• Cumplir requisitos legales o prevenir abusos.`
      },
      {
        heading: "4. Compartir información",
        content: `• No vendemos tu información personal.

• Los contenidos públicos podrán verse según la configuración de privacidad que elijas.

• Podremos compartir datos agregados (sin identificarte) con fines estadísticos.`
      },
      {
        heading: "5. Tus derechos",
        content: `• Podés decidir qué compartís y con quién.

• Podés editar o eliminar tu perfil o publicaciones.

• Podés revocar permisos desde los ajustes.`
      },
      {
        heading: "6. Seguridad y retención de datos",
        content: `• Protegemos tu información con medidas de seguridad razonables.

• Conservamos los datos solo el tiempo necesario para cumplir los fines establecidos.`
      },
      {
        heading: "7. Menores de edad",
        content: `Si tenés menos de 13 años, necesitás consentimiento parental.`
      },
      {
        heading: "8. Cambios",
        content: `Podemos actualizar esta Política y te avisaremos de cambios importantes.`
      },
      {
        heading: "9. Contacto",
        content: `Email: support@vyvapp.com

Dirección: San Diego, California, EE.UU.`
      }
    ]
  };

  const englishContent = {
    title: "PRIVACY POLICY",
    subtitle: "VYV (Visualize Your Vibe)",
    sections: [
      {
        heading: "1. Introduction",
        content: `Welcome to VYV ("we", "our"). VYV helps you improve wellness and personal productivity. This Privacy Policy explains how we collect, use, share, and protect information obtained through the app, including photos, posts, and social activity.
By using VYV, you agree to the data processing as described in this policy.

The application is available in multiple languages and can be used in the language the user prefers. The interface, texts, and messages will automatically adapt to the selected language, just like Instagram does.`
      },
      {
        heading: "2. Information We Collect",
        content: `• Data you provide (name, email, profile picture, posts, images, comments).

• Data generated by your app usage (schedules, habits, statistics, interactions).

• Technical data (IP address, device type, operating system).

• If you choose to link wearables or health apps, data such as steps, sleep hours, or heart rate may be read.`
      },
      {
        heading: "3. How We Use Your Information",
        content: `• To enable posting and viewing content.

• To personalize your experience and offer recommendations.

• To analyze app usage and improve it.

• To comply with legal requirements or prevent abuse.`
      },
      {
        heading: "4. Sharing Information",
        content: `• We do not sell your personal information.

• Public content may be viewed based on the privacy settings you choose.

• We may share aggregated data (without identifying you) for statistical purposes.`
      },
      {
        heading: "5. Your Rights",
        content: `• You can decide what you share and with whom.

• You can edit or delete your profile or posts.

• You can revoke permissions from settings.`
      },
      {
        heading: "6. Data Security & Retention",
        content: `• We protect your information with reasonable security measures.

• Data is retained only as long as necessary to fulfill the stated purposes.`
      },
      {
        heading: "7. Minors",
        content: `If you are under 13, you need parental consent.`
      },
      {
        heading: "8. Changes",
        content: `We may update this Policy and notify you of significant changes.`
      },
      {
        heading: "9. Contact",
        content: `Email: support@vyvapp.com

Address: San Diego, California, USA`
      }
    ]
  };

  const content = language === "es" ? spanishContent : englishContent;

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="sticky top-0 z-10 bg-background border-b border-border px-4 py-4">
          <div className="flex items-center justify-between">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => navigate(-1)}
              className="shrink-0"
            >
              <ArrowLeft className="h-5 w-5" />
            </Button>
            
            <Button
              variant="outline"
              size="sm"
              onClick={toggleLanguage}
              className="gap-2"
            >
              <Globe className="h-4 w-4" />
              {language === "es" ? t("legal.switchToEnglish") : t("legal.switchToSpanish")}
            </Button>
          </div>
        </div>

        {/* Content */}
        <ScrollArea className="h-[calc(100vh-73px)]">
          <div className="px-6 py-8">
            <div className="mb-8 text-center">
              <h1 className="text-3xl font-bold text-luxury-navy mb-2">
                {content.title}
              </h1>
              <p className="text-lg text-muted-foreground">{content.subtitle}</p>
            </div>

            <div className="space-y-8">
              {content.sections.map((section, index) => (
                <section key={index} className="space-y-3">
                  <h2 className="text-xl font-semibold text-luxury-navy">
                    {section.heading}
                  </h2>
                  <p className="text-foreground leading-relaxed whitespace-pre-line">
                    {section.content}
                  </p>
                </section>
              ))}
            </div>

            <div className="mt-12 pt-6 border-t border-border text-center text-sm text-muted-foreground">
              <p>{t("legal.lastUpdated")}</p>
            </div>
          </div>
        </ScrollArea>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
